//This code has been generated by the Console Notebook Command-line Interface. 
let studentsNames = ['Tom', 'Bill', 'Sally', 'Jim'];
let studentsGrades = [59,70,30,70];
let studentFail = [];

if(studentsNames.length === studentsGrades.length){console.log(`Number of Students: ${studentsNames.length}`);

    for(let i = 0; i < studentsGrades.length; i++){console.log(`${studentsNames[i]} grades is ${studentsGrades[i]}`);

        if(studentsGrades[i] < 60){
            studentFail.push(i);
        }
    }

}


for(let i = 0; i < studentFail.length; i++){
    console.log('Failed: ' + studentsNames[ studentFail[i] ]);
}


